module.exports={
    users:{
        'create:any':['*'],
        'read:any':['*'],
        'update:any':['*'],
        'delete:any':['*']
    },
    roles:{
        'create:any':['*'],
        'read:any':['*'],
        'update:any':['*'],
        'delete:any':['*']
    },
    banneds:{
        'create:any':['*'],
        'read:any':['*'],
        'update:any':['*'],
        'delete:any':['*']
    },
    types:{
        'create:any':['*'],
        'read:any':['*'],
        'update:any':['*'],
        'delete:any':['*']
    },
    job:{
        'create:any':['*'],
        'read:any':['*'],
        'update:any':['*'],
        'delete:any':['*']
    },
    candidates:{
        'create:any':['*'],
        'read:any':['*'],
        'update:any':['*'],
        'delete:any':['*']
    },
    proposal :{
        'create:any':['*'],
        'read:any':['*'],
        'update:any':['*'],
        'delete:any':['*']
    }
}