module.exports = {
    users:{
        'read:any':['*','!id']
    },
    roles:{
        'read:own':['*','!id','!user_id']
    },
    banneds:{
        'read:own':['*','!id','!user_id']
    },
    types:{
        'read:own':['*','!id','!user_id'],
    },
    job:{
        'read:own':['*','!id','!company_id','!status','!typing_id','!Candidate','!remaining'],
    },
    candidates:{
        'create:any':['*','!job_id'],
        'read:any':['*','!job_id'],
        'update:own':['*','!deliveryman_id','!job_id'],
        'delete:own':['*','!id','!deliveryman_id','!job_id','!candidate_type']
    }
}