module.exports = {
    users:{
        'read:any':['*','!id']
    },
    roles:{
        'read:own':['*','!id','!user_id']
    },
    banneds:{
        'read:own':['*','!id','!user_id']
    },
    types:{
        'read:own':['*','!id','!user_id'],
    },
    job:{
        'read:own':['*','!id','!company_id'],
    },
    candidates:{
        'create:any':['*','!tender_id'],
        'read:any':['*','!tender_id'],
        'update:own':['*','!deliveryman_id','!tender_id'],
        'delete:own':['*','!id','!deliveryman_id','!tender_id','!type_candidate']
    }
}