module.exports={
    users:{
        'create:any':['*'],
        'read:any':['*'],
        'update:own':['*'],
        'delete:own':['*']
    },
    roles:{
        'create:own':['*'],
        'read:any':['*'],
        'update:own':['*'],
        'delete:own':['*']
    },
    banneds:{
        'create:any':['*'],
        'read:any':['*'],
        'update:own':['*'],
        'delete:own':['*']
    },
    types:{
        'create:own':['*'],
        'read:any':['*'],
        'update:own':['*'],
        'delete:own':['*']
    },
    tenders:{
        'create:any':['*'],
        'read:any':['*'],
        'update:own':['*'],
        'delete:own':['*']
    },
    candidates:{
        'create:any':['*'],
        'read:any':['*'],
        'update:own':['*'],
        'delete:own':['*']
    }
}